### ISSUE TITLE
Dash in Finnish company organization number disappears at checkout

### ISSUE THREAD

**Issue by Flybring** [sveawebpay/svea-sdk-dotnet#263] opened 2024-03-12 20:36 UTC
I'm using preset values and specifying `9999999-2` as the value for the `NationalId` field. 
Upon reaching the checkout process the dash in the national id disappears, leading to a validation error. 

Could this behavior be attributed to the library, or might it be a problem with the API itself?

![image](https://github.com/sveawebpay/svea-sdk-dotnet/assets/19384053/51512518-4b71-45af-b5e3-42731a52bdcb)

**Comment by lounge** [comment] 2024-03-20 08:28
@Flybring It seems to be an issue with the API itself and it only appears if you set `IsReadonly = true` on the `NationalId` `PresetValue`.

**Comment by SebastianRuthstrom** [comment] 2024-03-20 09:40
Hi @Flybring ,
Yes as @lounge mentioned we found a issue in the API, which will be resolved ASAP. Meanwhile you can still use the preset value functionality NationalID, but skip the IsReadonly = true flag.

I will update with information here when the issue is resolved from our side.

Best regards, Sebastian

**Comment by Flybring** [comment] 2024-03-20 19:21
Okay, thank you for the update.

**Comment by SebastianRuthstrom** [comment] 2024-04-29 09:49
Hi @Flybring,
A fix for this was released 2024-04-18, now you can send NationalID as a preset value with IsReadonly = true in Finland in the correct format.

Best regards, Sebastian

**Closed as completed** 2024-05-07 19:17 UTC
Labels: wontfix
